function maximumDifference(nums: number[]): number {
    // Keeping track of running min of the array
    let min = nums[0]

    // Keeping track of the running highest diff
    let diff = -1;

    for (const num of nums) {

        // For each number update the minimum number
        min = Math.min(min, num);

        // For each number, update the diff between current number and min
        diff = Math.max(diff, num - min)
    }

    // If all the items are in decreasing order, the diff will be 0 as the max value will ve generated by taking a diff with itself
    // So, if diff ===0, we return -1, else we return diff 
    return diff ? diff : -1
};